name: envs398
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.9
    - pip
    - numpy
    - scipy
    - pandas
    - matplotlib
    - jupyter
    - jupyterlab
    - xarray
    - cartopy
    - netcdf4
    - cmocean
    - verde==1.6.*
    - boule==0.3.*
    - harmonica==0.4.*
    - pykdtree
    - numba
