name: envs398
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.9
    - pip
    - numpy
    - scipy
    - pandas
    - matplotlib
    - jupyter
    - jupyterlab
    - xarray
    - cartopy
    - conda-forge::netcdf4
    - conda-forge::libnetcdf
    - cmocean
    - verde==1.6.*
    - boule==0.3.*
    - harmonica==0.4.*
    - pykdtree
    - numba
